import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { isShipProvisioningPath, isMiningCommandCenterPath, isPilotTrainingPath } from "../app/pageRoute.ts";
import { matchLabel } from "./centerClient.ts";
test("standalone path is exact and leaves MCC/Training ownership intact",()=>{for(const p of ["/ship-provisioning","/ship-provisioning/"])assert.ok(isShipProvisioningPath(p));for(const p of ["/","/ship-provisioning/x","/pilot-training","/mining-command-center"])assert.equal(isShipProvisioningPath(p),false);assert.ok(isMiningCommandCenterPath("/mining-command-center"));assert.ok(isPilotTrainingPath("/pilot-training"));});
test("entry lazy mounts Center before App; Apply uses Center lifecycle without cockpit restore or target selection",()=>{const main=readFileSync(new URL("../main.ts",import.meta.url),"utf8"),page=readFileSync(new URL("../ui/ProvisioningCenter.svelte",import.meta.url),"utf8"),client=readFileSync(new URL("./centerClient.ts",import.meta.url),"utf8");assert.ok(main.indexOf('import("./ui/ProvisioningCenter.svelte")')<main.indexOf('import("./ui/App.svelte")'));assert.doesNotMatch(main,/import App from/);assert.doesNotMatch(page,/AppFlow|createClientStore|restoreSessions|setInterval|selectCharacter|Provision Ship|applyShip/);assert.doesNotMatch(client,/api\/bridge|sessionToken\.ts/);assert.match(client,/credentials: "omit"/);assert.match(page,/Apply accepted plan/);assert.match(page,/centerApply\(/);assert.match(page,/centerRoster\(token\)/);assert.doesNotMatch(readFileSync(new URL("../ui/Neocom.svelte",import.meta.url),"utf8"),/href="\/ship-provisioning"/);});
test("standalone Center stays an explicit secondary destination from cockpit and global chrome",()=>{for(const name of ["ProvisioningPanel.svelte","GlobalLaunchers.svelte"]){const source=readFileSync(new URL(`../ui/${name}`,import.meta.url),"utf8");assert.match(source,/href="\/ship-provisioning"/);assert.match(source,/Provisioning Center/);}const panel=readFileSync(new URL("../ui/ProvisioningPanel.svelte",import.meta.url),"utf8");assert.doesNotMatch(panel,/centerApply|centerLogin|centerRoster/);});
test("match words never infer a fitting name from a hull",()=>{assert.equal(matchLabel({state:"MODIFIED",alternatives:[]}),"Modified / no exact equipment match");assert.equal(matchLabel({state:"UNKNOWN",alternatives:[]}),"Fit unknown");assert.match(matchLabel({state:"AMBIGUOUS",alternatives:[{name:"First",definition:{} as any},{name:"Second",definition:{} as any}]}),/First.*Second/);});
